# Generated by Django 4.2.5 on 2023-10-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hard_disk',
            name='description',
            field=models.CharField(default='CORE I5/2,5/6GB/240GB', max_length=255),
        ),
        migrations.AddField(
            model_name='hard_disk',
            name='reason',
            field=models.CharField(default='Disuse', max_length=255),
        ),
    ]
