# Generated by Django 4.2.5 on 2023-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0002_hard_disk_description_hard_disk_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hard_disk',
            name='serialnumber',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
