# Generated by Django 4.2.5 on 2023-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0005_alter_desktop_area_alter_desktop_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposedDevice',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=30)),
                ('asset_number', models.IntegerField()),
                ('serial_number', models.CharField(max_length=255)),
                ('disk_serialnumber', models.CharField(max_length=255)),
                ('image', models.ImageField(default='images/default-avatar.png', upload_to='images/')),
                ('disposed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hard_disk',
            old_name='created_at',
            new_name='disposed_at',
        ),
        migrations.AddField(
            model_name='hard_disk',
            name='image',
            field=models.ImageField(default='images/default-avatar.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hard_disk',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
