# Generated by Django 4.2.5 on 2023-10-09 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposedDevice',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=30)),
                ('asset_number', models.IntegerField()),
                ('serial_number', models.CharField(max_length=255)),
                ('disk_serialnumber', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop')], default='desktop', max_length=10)),
                ('image', models.ImageField(default='images/default-avatar.png', upload_to='images/')),
                ('disposed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hard_Disk',
            fields=[
                ('serialnumber', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('size_gb', models.CharField(max_length=255, unique=True)),
                ('reason', models.CharField(default='Disuse', max_length=255)),
                ('image', models.ImageField(default='images/default-avatar.png', upload_to='images/')),
                ('disposed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=30)),
                ('asset_number', models.IntegerField()),
                ('serial_number', models.CharField(max_length=255)),
                ('disk_serialnumber', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop')], default='desktop', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
