# Generated by Django 4.2.5 on 2023-10-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0002_asset_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(default='images/default-avatar.png', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='hard_disk',
            name='size_gb',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physical.devicemodel'),
        ),
    ]
