# Generated by Django 4.2.5 on 2023-10-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0003_devicemodel_alter_hard_disk_size_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical.devicemodel'),
        ),
    ]
