# Generated by Django 4.2.5 on 2023-10-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0005_alter_devicemodel_image_alter_disposeddevice_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(choices=[('control de gestion', 'Control de Gestion'), ('presidencia', 'Presidencia'), ('office', 'Office'), ('planta baja', 'Planta Baja'), ('panol', 'panol'), ('planta', 'planta'), ('aceptacion', 'Aceptacion')], default='office', max_length=50),
        ),
    ]
