# Generated by Django 4.2.5 on 2023-10-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0007_asset_status_alter_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(choices=[('control de gestion', 'Control de Gestion'), ('presidencia', 'Presidencia'), ('office', 'Office'), ('planta baja', 'Planta Baja'), ('panol', 'Panol'), ('planta', 'Planta'), ('aceptacion', 'Aceptacion')], default='office', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('avaiable', 'Avaiable'), ('home office', 'Home office'), ('asigned', 'Asigned'), ('travel', 'Travel'), ('disposed', 'Disposed')], default='avaiable', max_length=50),
        ),
    ]
